### ISSUE TITLE
Read DCP crash in EDIFParser

### ISSUE THREAD

**Issue by pongstorn-xilinx** [Xilinx/RapidWright#415] opened 2022-05-11 16:30 UTC
Recent changes in master cause the crash while reading DCP.

**Comment by clavin-xlnx** [comment] 2022-07-06 20:37
@zhilix - I don't think this is the same error. However, could you post the example DCP or EDIF that is causing the issue?

**Comment by zhilix** [comment] 2022-07-07 01:23
FPGA03.zip
<https://drive.google.com/file/d/1U7Pf7GCXfJKeXg3BgYeXi788y81dxYZs/view?usp=drive_web>
Hi Chris,

Here is the dcp and edf file. It's large and I have to share with the link.
Thanks!

Zhili

**Comment by clavin-xlnx** [comment] 2022-07-07 03:50
> FPGA03.zip <https://drive.google.com/file/d/1U7Pf7GCXfJKeXg3BgYeXi788y81dxYZs/view?usp=drive_web> Hi Chris, Here is the dcp and edf file. It's large and I have to share with the link. Thanks! Zhili
Sorry Zhili, I couldn't access the file.  You might need to change sharing permissions.

**Comment by zhilix** [comment] 2022-07-07 03:52
I just updated the sharing, you can try now. Thanks

**Comment by clavin-xlnx** [comment] 2022-07-07 04:17
Just tried to run the design:

`java com.xilinx.rapidwright.interchange.PhysicalNetlistExample design.dcp design.edf design_out.dcp`

My output was:
```
Removing Parser@35966878, it started past the last cell.
Removing Parser@71933756, it started past the last cell.
Removing Parser@107900634, it started past the last cell.
Removing Parser@143867512, it started past the last cell.
Removing Parser@179834390, it started past the last cell.
Removing Parser@215801268, it started past the last cell.
Removing Parser@251768146, it started past the last cell.
==============================================================================
==                       DCP->Interchange Format->DCP                       ==
==============================================================================
                Read DCP:    20.077s
   Write Logical Netlist:     7.418s
  Write Physical Netlist:     0.095s
    Read Logical Netlist:    42.369s
   Read Physical Netlist:     0.507s
               Write DCP:     7.086s
------------------------------------------------------------------------------
         [No GC] *Total*:    77.552s
```

I was not able to reproduce the issue on the latest RapidWright from master.  Would you mind trying again after doing a `git pull` and `./gradlew update_jars` and re-compiling?

**Comment by zhilix** [comment] 2022-07-07 05:29
Thanks! I think I figured it out.
The thing is, If  I run the command  java com.xilinx.rapidwright.
interchange.PhysicalNetlistExample design.dcp design_out.dcp, without the
design.edf, there will be the errors;
but if I run the command with design.edf added like you used, it can
succeed.

**Comment by clavin-xlnx** [comment] 2022-10-21 16:14
Closing for now as I believe this was fixed.

**Closed by clavin-xlnx** 2022-10-21 16:14 UTC
